### ISSUE TITLE
Cant get dll's to load ?

### ISSUE THREAD

**Issue by geoffw123** [NLua/NLua#394] opened 2020-09-28 19:42 UTC
I used to use LuaInterface, which I understand this was derived from ? I am having problems with a simple test where I load some lua libraries with NLua

With LuaInterface I could use libraries such as lfs and lsqlite3 without a problem I just had a line such as 
require("lsqlite3")
or
local lfs = require "lfs"

These now give me a problem where I get an error

> error loading module 'lfs' from file 'C:\Program Files (x86)\Lua\5.1\clibs\lfs.dll':
> 	C:\Program Files (x86)\Lua\5.1\clibs\lfs.dll:1: syntax error near '<\144>'

Is this not supported in Nlua ?

**Comment by viniciusjarina** [comment] 2020-09-29 02:20
Hi @geoffw123 NLua p/Invoke into original Lua 5.4 dll 
Check if those modules works with Lua 5.4

**Comment by geoffw123** [comment] 2020-09-29 11:16
Hello Vinicius

Not sure If I understood your reply, but here is what I did.

Downloaded some windows binaries for Lua V 5.4
Then in a cmd window ran lua54 test.lua

test.lua contains require("lsqlite3")

this generates the exact same error as i got with Nlua

lua54: error loading module 'lsqlite3' from file 'C:\Program Files (x86)\Lua\5.1\clibs\lsqlite3.dll':        C:\Program Files (x86)\Lua\5.1\clibs\lsqlite3.dll:1: syntax error near '<\144>'

So the error is down to version incompatibility between my Lua V5.1 libraries and the later lua version you are using with Nlua

From what I have observed of the majority of us Windows lua users, a majority are still using Lua Version 5.1 as its the sweet spot and nothing very useful was added since V5.1. Trying to use later versions just give lots of compatibility headaches exactly like I have hit with this.

I dont suppose you want to provide a version of Nlua that works with lua v5.1 as its the version most people use ?

Looks like I am going to have to stick with the old LuaInterface I have been using for a while now.

Thanks again for your reply

Regards Geoff







________________________________

**Comment by viniciusjarina** [comment] 2020-09-29 17:56
Yeah. I understand. Lua 5.1 is almost 15 years old, the Lua team have added a bunch of fixes and improvements to the runtime and the language.

I decided to follow the Lua team, binding the NLua/KeraLua to the latest stable version of Lua, a lot of people have been asking to support Lua 5.1. But that would be similar if people ask me to support .NET 2.0 or Silverlight. I understand there are probably a lot of people who still uses Lua 5.1, and I bet there are people still using COBOL or VB6.

I did this project as a side project, I wasn't paid, I did because I want to use Lua with C# on iOS, Android and whatnot. 
But, since the project is open source and MIT licensed feel free to fork it and create your own variation using Lua 5.1.

If you do it, I will add the link to your project to the README and people will be able to use Lua 5.1

**Comment by geoffw123** [comment] 2020-09-29 18:42
Hi Vinicius  
Thanks for the reply and for providing NLua as an open source project, yes I understood you wouldnt want to support an  old version for Lua 5.1. I wouldnt be able to do this for myself as its way past my level of understanding of Lua.  I havent even figured out the difference between Keralua and Nlua !

**Comment by viniciusjarina** [comment] 2020-09-29 18:47
KeraLua is the low-level binding to the Lua C API, it basically maps 1 to 1
for every entry in the Lua54.dll.
http://www.lua.org/manual/5.4/manual.html#4
NLua uses KeraLua to integrate Lua and .NET using reflection (for instance
when you do foo:Bar() NLua will use reflection to find the method Bar in
the .NET object foo).

**Comment by viniciusjarina** [comment] 2020-10-01 17:54
Closing, since the issue is upstream 😉

**Closed by viniciusjarina** 2020-10-01 17:54 UTC
