### ISSUE TITLE
Access Violation on/after Lua.Close() in P/Invoke version

### ISSUE THREAD

**Issue by DaedalusGame** [NLua/NLua#192] opened 2016-02-15 19:38 UTC
I'm not even sure if this is an actual issue, considering that I only ever get it when I'm writing awful code?
I decided to compare with the KopiLua version and that version will run Lua.Close() and survive doing so, so I'm not sure which version is to be trusted on this but according to [this](http://stackoverflow.com/questions/10352092/prevent-lua-infinite-loop) stackoverflow question (and answers), the C-implementation of lua should survive a close call.

The (simplified and very terrible) code I'm running and tested on KopiLua aswell:

```
Lua lua = new Lua();
Thread Worker = new Thread(() => { try { lua.DoString(@"while(true) do print(""blah"") end"); } catch { } });
Worker.Start();
if (!Worker.Join(3000))
     lua.Close();
while (true);
```

(the while(true) at the end is so the console application doesn't terminate)

**Comment by viniciusjarina** [comment] 2019-03-01 04:21
The program stay in your `while(true)` forever.
In theory closing should work, but remember Lua is not thread safe by design, so if you want avoid infinite loop you should use other methods for sand boxing, like using hooks e limit the number of instructions executed

**Closed by viniciusjarina** 2019-03-01 04:21 UTC
